stages:
    - prep
    - build
    - test

prepare a car:
    stage:
        prep
    script:
        - mkdir build
        - touch build/car.txt
    artifacts:
        paths:
            - build/

build the car:
    stage:
        build
    script:
        - echo 'chassis' >> build/car.txt
        - echo 'engine' >> build/car.txt
        - echo 'wheels' >> build/car.txt
    artifacts:
        paths:
          - build/

author a car catalog:
    stage:
        build
    script:
        - mkdir meta
        - echo $GITLAB_USER_NAME >> meta/author.txt
    artifacts:
        paths:
            - meta/

test the car:
    stage:
        test
    script:
        - test -f build/car.txt
        - cd build
        - grep "chassis" car.txt
        - grep "engine" car.txt
        - grep "wheels" car.txt
